### ISSUE TITLE
Smelting both Enite and Diamond doesn't work for Blast Furnace

### ISSUE THREAD

**Issue by tuguzD** [CuteRayDev/Endonium#3]
And I think it's pretty strange, because we can smelt Ancient Debris both in blast and regular furnace.

![Blast Furnace](https://user-images.githubusercontent.com/56772528/150414203-89bef15d-9d2d-40c4-8068-bb07264156a7.png)

![Furnace](https://user-images.githubusercontent.com/56772528/150414206-6acb1c93-0421-40f0-b20b-de028c774ea9.png)

**Comment by CuteRayDev** [comment]
This is pretty easy to fix! I forgot to patch this in the 1.1.3 patch tho, so it is in the next update
